# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'THREDDS_Explorer_extract_Multi_WMS_dockwidget_base_7.ui'
#
# Created: Tue Mar 14 10:49:44 2017
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_THREDDSViewer(object):
    def setupUi(self, THREDDSViewer):
        THREDDSViewer.setObjectName(_fromUtf8("THREDDSViewer"))
        THREDDSViewer.resize(550, 836)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget_Multi_WMS = QtGui.QTabWidget(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_Multi_WMS.sizePolicy().hasHeightForWidth())
        self.tabWidget_Multi_WMS.setSizePolicy(sizePolicy)
        self.tabWidget_Multi_WMS.setMinimumSize(QtCore.QSize(1, 0))
        self.tabWidget_Multi_WMS.setMaximumSize(QtCore.QSize(524287, 524287))
        self.tabWidget_Multi_WMS.setObjectName(_fromUtf8("tabWidget_Multi_WMS"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_39 = QtGui.QGridLayout(self.tab)
        self.gridLayout_39.setObjectName(_fromUtf8("gridLayout_39"))
        self.scrollArea_7 = QtGui.QScrollArea(self.tab)
        self.scrollArea_7.setMaximumSize(QtCore.QSize(167777, 167777))
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollArea_7.setObjectName(_fromUtf8("scrollArea_7"))
        self.scrollAreaWidgetContents_4 = QtGui.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, -84, 507, 807))
        self.scrollAreaWidgetContents_4.setObjectName(_fromUtf8("scrollAreaWidgetContents_4"))
        self.gridLayout_38 = QtGui.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_38.setObjectName(_fromUtf8("gridLayout_38"))
        self.combo_dataset_cmems_list = QtGui.QComboBox(self.scrollAreaWidgetContents_4)
        self.combo_dataset_cmems_list.setObjectName(_fromUtf8("combo_dataset_cmems_list"))
        self.gridLayout_38.addWidget(self.combo_dataset_cmems_list, 6, 0, 1, 1)
        self.combo_area_list = QtGui.QComboBox(self.scrollAreaWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_area_list.sizePolicy().hasHeightForWidth())
        self.combo_area_list.setSizePolicy(sizePolicy)
        self.combo_area_list.setObjectName(_fromUtf8("combo_area_list"))
        self.gridLayout_38.addWidget(self.combo_area_list, 2, 0, 1, 1)
        self.combo_product_list = QtGui.QComboBox(self.scrollAreaWidgetContents_4)
        self.combo_product_list.setObjectName(_fromUtf8("combo_product_list"))
        self.gridLayout_38.addWidget(self.combo_product_list, 4, 0, 1, 1)
        self.label_product_3 = QtGui.QLabel(self.scrollAreaWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_product_3.sizePolicy().hasHeightForWidth())
        self.label_product_3.setSizePolicy(sizePolicy)
        self.label_product_3.setObjectName(_fromUtf8("label_product_3"))
        self.gridLayout_38.addWidget(self.label_product_3, 3, 0, 1, 1)
        self.label_variable_3 = QtGui.QLabel(self.scrollAreaWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_variable_3.sizePolicy().hasHeightForWidth())
        self.label_variable_3.setSizePolicy(sizePolicy)
        self.label_variable_3.setObjectName(_fromUtf8("label_variable_3"))
        self.gridLayout_38.addWidget(self.label_variable_3, 7, 0, 1, 1)
        self.label_dataset_3 = QtGui.QLabel(self.scrollAreaWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_dataset_3.sizePolicy().hasHeightForWidth())
        self.label_dataset_3.setSizePolicy(sizePolicy)
        self.label_dataset_3.setObjectName(_fromUtf8("label_dataset_3"))
        self.gridLayout_38.addWidget(self.label_dataset_3, 5, 0, 1, 1)
        self.combo_variable_list = QtGui.QComboBox(self.scrollAreaWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_variable_list.sizePolicy().hasHeightForWidth())
        self.combo_variable_list.setSizePolicy(sizePolicy)
        self.combo_variable_list.setObjectName(_fromUtf8("combo_variable_list"))
        self.gridLayout_38.addWidget(self.combo_variable_list, 8, 0, 1, 1)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.verticalLayout_7.setContentsMargins(-1, -1, 4, 6)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.ExtractWidget_4 = QtGui.QTabWidget(self.scrollAreaWidgetContents_4)
        self.ExtractWidget_4.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExtractWidget_4.sizePolicy().hasHeightForWidth())
        self.ExtractWidget_4.setSizePolicy(sizePolicy)
        self.ExtractWidget_4.setMaximumSize(QtCore.QSize(524287, 524287))
        self.ExtractWidget_4.setObjectName(_fromUtf8("ExtractWidget_4"))
        self.tab_WMS_7 = QtGui.QWidget()
        self.tab_WMS_7.setObjectName(_fromUtf8("tab_WMS_7"))
        self.gridLayout_34 = QtGui.QGridLayout(self.tab_WMS_7)
        self.gridLayout_34.setObjectName(_fromUtf8("gridLayout_34"))
        self.label_9 = QtGui.QLabel(self.tab_WMS_7)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_34.addWidget(self.label_9, 3, 0, 1, 1)
        self.tab_WMS_layout_7 = QtGui.QVBoxLayout()
        self.tab_WMS_layout_7.setSpacing(0)
        self.tab_WMS_layout_7.setObjectName(_fromUtf8("tab_WMS_layout_7"))
        self.label_depth_3 = QtGui.QLabel(self.tab_WMS_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_depth_3.sizePolicy().hasHeightForWidth())
        self.label_depth_3.setSizePolicy(sizePolicy)
        self.label_depth_3.setObjectName(_fromUtf8("label_depth_3"))
        self.tab_WMS_layout_7.addWidget(self.label_depth_3)
        self.combo_wms_layer_depth = QtGui.QComboBox(self.tab_WMS_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_wms_layer_depth.sizePolicy().hasHeightForWidth())
        self.combo_wms_layer_depth.setSizePolicy(sizePolicy)
        self.combo_wms_layer_depth.setMaximumSize(QtCore.QSize(400, 20))
        self.combo_wms_layer_depth.setObjectName(_fromUtf8("combo_wms_layer_depth"))
        self.tab_WMS_layout_7.addWidget(self.combo_wms_layer_depth)
        self.gridLayout_35 = QtGui.QGridLayout()
        self.gridLayout_35.setVerticalSpacing(0)
        self.gridLayout_35.setObjectName(_fromUtf8("gridLayout_35"))
        self.combo_proj = QtGui.QComboBox(self.tab_WMS_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_proj.sizePolicy().hasHeightForWidth())
        self.combo_proj.setSizePolicy(sizePolicy)
        self.combo_proj.setMaximumSize(QtCore.QSize(16777215, 20))
        self.combo_proj.setObjectName(_fromUtf8("combo_proj"))
        self.gridLayout_35.addWidget(self.combo_proj, 1, 1, 1, 1)
        self.label_style_3 = QtGui.QLabel(self.tab_WMS_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_style_3.sizePolicy().hasHeightForWidth())
        self.label_style_3.setSizePolicy(sizePolicy)
        self.label_style_3.setObjectName(_fromUtf8("label_style_3"))
        self.gridLayout_35.addWidget(self.label_style_3, 0, 0, 1, 1)
        self.combo_colorbar = QtGui.QComboBox(self.tab_WMS_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_colorbar.sizePolicy().hasHeightForWidth())
        self.combo_colorbar.setSizePolicy(sizePolicy)
        self.combo_colorbar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.combo_colorbar.setObjectName(_fromUtf8("combo_colorbar"))
        self.gridLayout_35.addWidget(self.combo_colorbar, 1, 0, 1, 1)
        self.tab_WMS_layout_7.addLayout(self.gridLayout_35)
        self.WMSLabelTimeRange_9 = QtGui.QLabel(self.tab_WMS_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WMSLabelTimeRange_9.sizePolicy().hasHeightForWidth())
        self.WMSLabelTimeRange_9.setSizePolicy(sizePolicy)
        self.WMSLabelTimeRange_9.setMinimumSize(QtCore.QSize(300, 0))
        self.WMSLabelTimeRange_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.WMSLabelTimeRange_9.setIndent(-1)
        self.WMSLabelTimeRange_9.setObjectName(_fromUtf8("WMSLabelTimeRange_9"))
        self.tab_WMS_layout_7.addWidget(self.WMSLabelTimeRange_9)
        self.layout_time_7 = QtGui.QGridLayout()
        self.layout_time_7.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.layout_time_7.setHorizontalSpacing(6)
        self.layout_time_7.setVerticalSpacing(2)
        self.layout_time_7.setObjectName(_fromUtf8("layout_time_7"))
        self.combo_wms_time_last_d = QtGui.QComboBox(self.tab_WMS_7)
        self.combo_wms_time_last_d.setMaximumSize(QtCore.QSize(16777215, 20))
        self.combo_wms_time_last_d.setObjectName(_fromUtf8("combo_wms_time_last_d"))
        self.layout_time_7.addWidget(self.combo_wms_time_last_d, 1, 0, 1, 1)
        self.combo_wms_time_first_d = QtGui.QComboBox(self.tab_WMS_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_wms_time_first_d.sizePolicy().hasHeightForWidth())
        self.combo_wms_time_first_d.setSizePolicy(sizePolicy)
        self.combo_wms_time_first_d.setMaximumSize(QtCore.QSize(16777215, 20))
        self.combo_wms_time_first_d.setObjectName(_fromUtf8("combo_wms_time_first_d"))
        self.layout_time_7.addWidget(self.combo_wms_time_first_d, 0, 0, 1, 1)
        self.combo_wms_time_first_h = QtGui.QComboBox(self.tab_WMS_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_wms_time_first_h.sizePolicy().hasHeightForWidth())
        self.combo_wms_time_first_h.setSizePolicy(sizePolicy)
        self.combo_wms_time_first_h.setMaximumSize(QtCore.QSize(16777215, 20))
        self.combo_wms_time_first_h.setObjectName(_fromUtf8("combo_wms_time_first_h"))
        self.layout_time_7.addWidget(self.combo_wms_time_first_h, 0, 1, 1, 1)
        self.combo_wms_time_last_h = QtGui.QComboBox(self.tab_WMS_7)
        self.combo_wms_time_last_h.setMaximumSize(QtCore.QSize(16777215, 20))
        self.combo_wms_time_last_h.setObjectName(_fromUtf8("combo_wms_time_last_h"))
        self.layout_time_7.addWidget(self.combo_wms_time_last_h, 1, 1, 1, 1)
        self.tab_WMS_layout_7.addLayout(self.layout_time_7)
        self.label_12 = QtGui.QLabel(self.tab_WMS_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.tab_WMS_layout_7.addWidget(self.label_12)
        self.WMS_Bounds_9 = QtGui.QGridLayout()
        self.WMS_Bounds_9.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.WMS_Bounds_9.setHorizontalSpacing(5)
        self.WMS_Bounds_9.setVerticalSpacing(1)
        self.WMS_Bounds_9.setObjectName(_fromUtf8("WMS_Bounds_9"))
        self.lat_WMS_northBound = QtGui.QLineEdit(self.tab_WMS_7)
        self.lat_WMS_northBound.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lat_WMS_northBound.sizePolicy().hasHeightForWidth())
        self.lat_WMS_northBound.setSizePolicy(sizePolicy)
        self.lat_WMS_northBound.setMaximumSize(QtCore.QSize(16777215, 22))
        self.lat_WMS_northBound.setObjectName(_fromUtf8("lat_WMS_northBound"))
        self.WMS_Bounds_9.addWidget(self.lat_WMS_northBound, 0, 1, 1, 1)
        self.lat_WMS_southBound = QtGui.QLineEdit(self.tab_WMS_7)
        self.lat_WMS_southBound.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lat_WMS_southBound.sizePolicy().hasHeightForWidth())
        self.lat_WMS_southBound.setSizePolicy(sizePolicy)
        self.lat_WMS_southBound.setMaximumSize(QtCore.QSize(16777215, 22))
        self.lat_WMS_southBound.setObjectName(_fromUtf8("lat_WMS_southBound"))
        self.WMS_Bounds_9.addWidget(self.lat_WMS_southBound, 2, 1, 1, 1)
        self.lon_WMS_eastBound = QtGui.QLineEdit(self.tab_WMS_7)
        self.lon_WMS_eastBound.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lon_WMS_eastBound.sizePolicy().hasHeightForWidth())
        self.lon_WMS_eastBound.setSizePolicy(sizePolicy)
        self.lon_WMS_eastBound.setMaximumSize(QtCore.QSize(16777215, 22))
        self.lon_WMS_eastBound.setObjectName(_fromUtf8("lon_WMS_eastBound"))
        self.WMS_Bounds_9.addWidget(self.lon_WMS_eastBound, 1, 2, 1, 1)
        self.lon_WMS_westBound = QtGui.QLineEdit(self.tab_WMS_7)
        self.lon_WMS_westBound.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lon_WMS_westBound.sizePolicy().hasHeightForWidth())
        self.lon_WMS_westBound.setSizePolicy(sizePolicy)
        self.lon_WMS_westBound.setMinimumSize(QtCore.QSize(0, 0))
        self.lon_WMS_westBound.setMaximumSize(QtCore.QSize(16777215, 22))
        self.lon_WMS_westBound.setObjectName(_fromUtf8("lon_WMS_westBound"))
        self.WMS_Bounds_9.addWidget(self.lon_WMS_westBound, 1, 0, 1, 1)
        self.tab_WMS_layout_7.addLayout(self.WMS_Bounds_9)
        self.gridLayout_34.addLayout(self.tab_WMS_layout_7, 0, 0, 3, 1)
        self.gridLayout_36 = QtGui.QGridLayout()
        self.gridLayout_36.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout_36.setHorizontalSpacing(6)
        self.gridLayout_36.setVerticalSpacing(0)
        self.gridLayout_36.setObjectName(_fromUtf8("gridLayout_36"))
        self.Xparallels_value = QtGui.QLineEdit(self.tab_WMS_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Xparallels_value.sizePolicy().hasHeightForWidth())
        self.Xparallels_value.setSizePolicy(sizePolicy)
        self.Xparallels_value.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Xparallels_value.setObjectName(_fromUtf8("Xparallels_value"))
        self.gridLayout_36.addWidget(self.Xparallels_value, 12, 0, 1, 1)
        self.checkBox_arc = QtGui.QCheckBox(self.tab_WMS_7)
        self.checkBox_arc.setObjectName(_fromUtf8("checkBox_arc"))
        self.gridLayout_36.addWidget(self.checkBox_arc, 13, 0, 1, 1)
        self.nbcolors_value = QtGui.QLineEdit(self.tab_WMS_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nbcolors_value.sizePolicy().hasHeightForWidth())
        self.nbcolors_value.setSizePolicy(sizePolicy)
        self.nbcolors_value.setMaximumSize(QtCore.QSize(16777215, 20))
        self.nbcolors_value.setObjectName(_fromUtf8("nbcolors_value"))
        self.gridLayout_36.addWidget(self.nbcolors_value, 10, 3, 1, 1)
        self.label_Ymedians_3 = QtGui.QLabel(self.tab_WMS_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Ymedians_3.sizePolicy().hasHeightForWidth())
        self.label_Ymedians_3.setSizePolicy(sizePolicy)
        self.label_Ymedians_3.setObjectName(_fromUtf8("label_Ymedians_3"))
        self.gridLayout_36.addWidget(self.label_Ymedians_3, 11, 1, 1, 1)
        self.Xpixels_value = QtGui.QLineEdit(self.tab_WMS_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Xpixels_value.sizePolicy().hasHeightForWidth())
        self.Xpixels_value.setSizePolicy(sizePolicy)
        self.Xpixels_value.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Xpixels_value.setObjectName(_fromUtf8("Xpixels_value"))
        self.gridLayout_36.addWidget(self.Xpixels_value, 12, 3, 1, 1)
        self.label_Xparallels_3 = QtGui.QLabel(self.tab_WMS_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Xparallels_3.sizePolicy().hasHeightForWidth())
        self.label_Xparallels_3.setSizePolicy(sizePolicy)
        self.label_Xparallels_3.setObjectName(_fromUtf8("label_Xparallels_3"))
        self.gridLayout_36.addWidget(self.label_Xparallels_3, 11, 0, 1, 1)
        self.checkBox_ant = QtGui.QCheckBox(self.tab_WMS_7)
        self.checkBox_ant.setObjectName(_fromUtf8("checkBox_ant"))
        self.gridLayout_36.addWidget(self.checkBox_ant, 13, 1, 1, 1)
        self.minscale_value = QtGui.QLineEdit(self.tab_WMS_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minscale_value.sizePolicy().hasHeightForWidth())
        self.minscale_value.setSizePolicy(sizePolicy)
        self.minscale_value.setMinimumSize(QtCore.QSize(22, 0))
        self.minscale_value.setMaximumSize(QtCore.QSize(16777215, 20))
        self.minscale_value.setObjectName(_fromUtf8("minscale_value"))
        self.gridLayout_36.addWidget(self.minscale_value, 10, 0, 1, 1)
        self.Ymedians_value = QtGui.QLineEdit(self.tab_WMS_7)
        self.Ymedians_value.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ymedians_value.sizePolicy().hasHeightForWidth())
        self.Ymedians_value.setSizePolicy(sizePolicy)
        self.Ymedians_value.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Ymedians_value.setObjectName(_fromUtf8("Ymedians_value"))
        self.gridLayout_36.addWidget(self.Ymedians_value, 12, 1, 1, 1)
        self.label_minscale_3 = QtGui.QLabel(self.tab_WMS_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_minscale_3.sizePolicy().hasHeightForWidth())
        self.label_minscale_3.setSizePolicy(sizePolicy)
        self.label_minscale_3.setObjectName(_fromUtf8("label_minscale_3"))
        self.gridLayout_36.addWidget(self.label_minscale_3, 9, 0, 1, 1)
        self.label_nbcolors_3 = QtGui.QLabel(self.tab_WMS_7)
        self.label_nbcolors_3.setObjectName(_fromUtf8("label_nbcolors_3"))
        self.gridLayout_36.addWidget(self.label_nbcolors_3, 9, 3, 1, 1)
        self.label_Xpixels_3 = QtGui.QLabel(self.tab_WMS_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Xpixels_3.sizePolicy().hasHeightForWidth())
        self.label_Xpixels_3.setSizePolicy(sizePolicy)
        self.label_Xpixels_3.setObjectName(_fromUtf8("label_Xpixels_3"))
        self.gridLayout_36.addWidget(self.label_Xpixels_3, 11, 3, 1, 1)
        self.maxscale_value = QtGui.QLineEdit(self.tab_WMS_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxscale_value.sizePolicy().hasHeightForWidth())
        self.maxscale_value.setSizePolicy(sizePolicy)
        self.maxscale_value.setMaximumSize(QtCore.QSize(16777215, 20))
        self.maxscale_value.setObjectName(_fromUtf8("maxscale_value"))
        self.gridLayout_36.addWidget(self.maxscale_value, 10, 1, 1, 1)
        self.label_maxscale_3 = QtGui.QLabel(self.tab_WMS_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_maxscale_3.sizePolicy().hasHeightForWidth())
        self.label_maxscale_3.setSizePolicy(sizePolicy)
        self.label_maxscale_3.setObjectName(_fromUtf8("label_maxscale_3"))
        self.gridLayout_36.addWidget(self.label_maxscale_3, 9, 1, 1, 1)
        self.checkBox_log = QtGui.QCheckBox(self.tab_WMS_7)
        self.checkBox_log.setObjectName(_fromUtf8("checkBox_log"))
        self.gridLayout_36.addWidget(self.checkBox_log, 13, 3, 1, 1)
        self.gridLayout_34.addLayout(self.gridLayout_36, 4, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_WMS_7)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.button_req_map_plot_cmems = QtGui.QPushButton(self.groupBox_4)
        self.button_req_map_plot_cmems.setEnabled(True)
        self.button_req_map_plot_cmems.setGeometry(QtCore.QRect(110, 0, 191, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_req_map_plot_cmems.sizePolicy().hasHeightForWidth())
        self.button_req_map_plot_cmems.setSizePolicy(sizePolicy)
        self.button_req_map_plot_cmems.setMinimumSize(QtCore.QSize(0, 24))
        self.button_req_map_plot_cmems.setMaximumSize(QtCore.QSize(250, 25))
        self.button_req_map_plot_cmems.setObjectName(_fromUtf8("button_req_map_plot_cmems"))
        self.button_req_animation_plot = QtGui.QPushButton(self.groupBox_4)
        self.button_req_animation_plot.setGeometry(QtCore.QRect(110, 30, 191, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_req_animation_plot.sizePolicy().hasHeightForWidth())
        self.button_req_animation_plot.setSizePolicy(sizePolicy)
        self.button_req_animation_plot.setMinimumSize(QtCore.QSize(20, 20))
        self.button_req_animation_plot.setMaximumSize(QtCore.QSize(280, 25))
        self.button_req_animation_plot.setIconSize(QtCore.QSize(24, 24))
        self.button_req_animation_plot.setObjectName(_fromUtf8("button_req_animation_plot"))
        self.gridLayout_34.addWidget(self.groupBox_4, 5, 0, 1, 1)
        self.ExtractWidget_4.addTab(self.tab_WMS_7, _fromUtf8(""))
        self.tab_WCS_7 = QtGui.QWidget()
        self.tab_WCS_7.setObjectName(_fromUtf8("tab_WCS_7"))
        self.gridLayout_37 = QtGui.QGridLayout(self.tab_WCS_7)
        self.gridLayout_37.setObjectName(_fromUtf8("gridLayout_37"))
        self.tab_WCS_layout_7 = QtGui.QVBoxLayout()
        self.tab_WCS_layout_7.setObjectName(_fromUtf8("tab_WCS_layout_7"))
        self.combo_wcs_coverage = QtGui.QComboBox(self.tab_WCS_7)
        self.combo_wcs_coverage.setMinimumSize(QtCore.QSize(22, 22))
        self.combo_wcs_coverage.setObjectName(_fromUtf8("combo_wcs_coverage"))
        self.tab_WCS_layout_7.addWidget(self.combo_wcs_coverage)
        self.WCSLabelTimeRange = QtGui.QLabel(self.tab_WCS_7)
        self.WCSLabelTimeRange.setMaximumSize(QtCore.QSize(16777215, 25))
        self.WCSLabelTimeRange.setObjectName(_fromUtf8("WCSLabelTimeRange"))
        self.tab_WCS_layout_7.addWidget(self.WCSLabelTimeRange)
        self.combo_wcs_time = QtGui.QComboBox(self.tab_WCS_7)
        self.combo_wcs_time.setObjectName(_fromUtf8("combo_wcs_time"))
        self.tab_WCS_layout_7.addWidget(self.combo_wcs_time)
        self.combo_wcs_time_last = QtGui.QComboBox(self.tab_WCS_7)
        self.combo_wcs_time_last.setObjectName(_fromUtf8("combo_wcs_time_last"))
        self.tab_WCS_layout_7.addWidget(self.combo_wcs_time_last)
        self.WCSBoundingBoxInfo_7 = QtGui.QLabel(self.tab_WCS_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WCSBoundingBoxInfo_7.sizePolicy().hasHeightForWidth())
        self.WCSBoundingBoxInfo_7.setSizePolicy(sizePolicy)
        self.WCSBoundingBoxInfo_7.setMaximumSize(QtCore.QSize(200, 20))
        self.WCSBoundingBoxInfo_7.setObjectName(_fromUtf8("WCSBoundingBoxInfo_7"))
        self.tab_WCS_layout_7.addWidget(self.WCSBoundingBoxInfo_7)
        self.WCS_Bounds_7 = QtGui.QGridLayout()
        self.WCS_Bounds_7.setObjectName(_fromUtf8("WCS_Bounds_7"))
        self.WCS_southBound = QtGui.QLineEdit(self.tab_WCS_7)
        self.WCS_southBound.setObjectName(_fromUtf8("WCS_southBound"))
        self.WCS_Bounds_7.addWidget(self.WCS_southBound, 2, 1, 1, 1)
        self.WCS_northBound = QtGui.QLineEdit(self.tab_WCS_7)
        self.WCS_northBound.setObjectName(_fromUtf8("WCS_northBound"))
        self.WCS_Bounds_7.addWidget(self.WCS_northBound, 0, 1, 1, 1)
        self.WCS_westBound = QtGui.QLineEdit(self.tab_WCS_7)
        self.WCS_westBound.setObjectName(_fromUtf8("WCS_westBound"))
        self.WCS_Bounds_7.addWidget(self.WCS_westBound, 1, 0, 1, 1)
        self.WCS_eastBound = QtGui.QLineEdit(self.tab_WCS_7)
        self.WCS_eastBound.setObjectName(_fromUtf8("WCS_eastBound"))
        self.WCS_Bounds_7.addWidget(self.WCS_eastBound, 1, 2, 1, 1)
        self.tab_WCS_layout_7.addLayout(self.WCS_Bounds_7)
        self.gridLayout_37.addLayout(self.tab_WCS_layout_7, 0, 0, 1, 1)
        self.ExtractWidget_4.addTab(self.tab_WCS_7, _fromUtf8(""))
        self.tab_WPS_4 = QtGui.QWidget()
        self.tab_WPS_4.setObjectName(_fromUtf8("tab_WPS_4"))
        self.ExtractWidget_4.addTab(self.tab_WPS_4, _fromUtf8(""))
        self.tab_Extract_4 = QtGui.QWidget()
        self.tab_Extract_4.setObjectName(_fromUtf8("tab_Extract_4"))
        self.label_depth_6 = QtGui.QLabel(self.tab_Extract_4)
        self.label_depth_6.setGeometry(QtCore.QRect(10, 20, 527, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_depth_6.sizePolicy().hasHeightForWidth())
        self.label_depth_6.setSizePolicy(sizePolicy)
        self.label_depth_6.setObjectName(_fromUtf8("label_depth_6"))
        self.combo_wms_layer_depth_2 = QtGui.QComboBox(self.tab_Extract_4)
        self.combo_wms_layer_depth_2.setGeometry(QtCore.QRect(10, 60, 161, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_wms_layer_depth_2.sizePolicy().hasHeightForWidth())
        self.combo_wms_layer_depth_2.setSizePolicy(sizePolicy)
        self.combo_wms_layer_depth_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.combo_wms_layer_depth_2.setObjectName(_fromUtf8("combo_wms_layer_depth_2"))
        self.WMSLabelTimeRange_10 = QtGui.QLabel(self.tab_Extract_4)
        self.WMSLabelTimeRange_10.setGeometry(QtCore.QRect(10, 100, 527, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WMSLabelTimeRange_10.sizePolicy().hasHeightForWidth())
        self.WMSLabelTimeRange_10.setSizePolicy(sizePolicy)
        self.WMSLabelTimeRange_10.setObjectName(_fromUtf8("WMSLabelTimeRange_10"))
        self.layoutWidget_10 = QtGui.QWidget(self.tab_Extract_4)
        self.layoutWidget_10.setGeometry(QtCore.QRect(0, 130, 391, 71))
        self.layoutWidget_10.setObjectName(_fromUtf8("layoutWidget_10"))
        self.layout_time_8 = QtGui.QGridLayout(self.layoutWidget_10)
        self.layout_time_8.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.layout_time_8.setSpacing(6)
        self.layout_time_8.setMargin(0)
        self.layout_time_8.setObjectName(_fromUtf8("layout_time_8"))
        self.combo_wms_time_last_d_2 = QtGui.QComboBox(self.layoutWidget_10)
        self.combo_wms_time_last_d_2.setObjectName(_fromUtf8("combo_wms_time_last_d_2"))
        self.layout_time_8.addWidget(self.combo_wms_time_last_d_2, 1, 0, 1, 1)
        self.combo_wms_time_last_h_2 = QtGui.QComboBox(self.layoutWidget_10)
        self.combo_wms_time_last_h_2.setObjectName(_fromUtf8("combo_wms_time_last_h_2"))
        self.layout_time_8.addWidget(self.combo_wms_time_last_h_2, 1, 1, 1, 1)
        self.combo_wms_time_first_d_2 = QtGui.QComboBox(self.layoutWidget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_wms_time_first_d_2.sizePolicy().hasHeightForWidth())
        self.combo_wms_time_first_d_2.setSizePolicy(sizePolicy)
        self.combo_wms_time_first_d_2.setObjectName(_fromUtf8("combo_wms_time_first_d_2"))
        self.layout_time_8.addWidget(self.combo_wms_time_first_d_2, 0, 0, 1, 1)
        self.combo_wms_time_first_h_2 = QtGui.QComboBox(self.layoutWidget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_wms_time_first_h_2.sizePolicy().hasHeightForWidth())
        self.combo_wms_time_first_h_2.setSizePolicy(sizePolicy)
        self.combo_wms_time_first_h_2.setObjectName(_fromUtf8("combo_wms_time_first_h_2"))
        self.layout_time_8.addWidget(self.combo_wms_time_first_h_2, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab_Extract_4)
        self.label_13.setGeometry(QtCore.QRect(10, 220, 527, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.layoutWidget_11 = QtGui.QWidget(self.tab_Extract_4)
        self.layoutWidget_11.setGeometry(QtCore.QRect(0, 250, 391, 111))
        self.layoutWidget_11.setObjectName(_fromUtf8("layoutWidget_11"))
        self.WMS_Bounds_10 = QtGui.QGridLayout(self.layoutWidget_11)
        self.WMS_Bounds_10.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.WMS_Bounds_10.setMargin(0)
        self.WMS_Bounds_10.setObjectName(_fromUtf8("WMS_Bounds_10"))
        self.lat_WMS_northBound_2 = QtGui.QLineEdit(self.layoutWidget_11)
        self.lat_WMS_northBound_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lat_WMS_northBound_2.sizePolicy().hasHeightForWidth())
        self.lat_WMS_northBound_2.setSizePolicy(sizePolicy)
        self.lat_WMS_northBound_2.setMinimumSize(QtCore.QSize(100, 0))
        self.lat_WMS_northBound_2.setMaximumSize(QtCore.QSize(200, 30))
        self.lat_WMS_northBound_2.setObjectName(_fromUtf8("lat_WMS_northBound_2"))
        self.WMS_Bounds_10.addWidget(self.lat_WMS_northBound_2, 0, 1, 1, 1)
        self.lon_WMS_westBound_2 = QtGui.QLineEdit(self.layoutWidget_11)
        self.lon_WMS_westBound_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lon_WMS_westBound_2.sizePolicy().hasHeightForWidth())
        self.lon_WMS_westBound_2.setSizePolicy(sizePolicy)
        self.lon_WMS_westBound_2.setMinimumSize(QtCore.QSize(100, 9))
        self.lon_WMS_westBound_2.setMaximumSize(QtCore.QSize(200, 30))
        self.lon_WMS_westBound_2.setObjectName(_fromUtf8("lon_WMS_westBound_2"))
        self.WMS_Bounds_10.addWidget(self.lon_WMS_westBound_2, 1, 0, 1, 1)
        self.lat_WMS_southBound_2 = QtGui.QLineEdit(self.layoutWidget_11)
        self.lat_WMS_southBound_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lat_WMS_southBound_2.sizePolicy().hasHeightForWidth())
        self.lat_WMS_southBound_2.setSizePolicy(sizePolicy)
        self.lat_WMS_southBound_2.setMinimumSize(QtCore.QSize(100, 0))
        self.lat_WMS_southBound_2.setMaximumSize(QtCore.QSize(200, 30))
        self.lat_WMS_southBound_2.setObjectName(_fromUtf8("lat_WMS_southBound_2"))
        self.WMS_Bounds_10.addWidget(self.lat_WMS_southBound_2, 2, 1, 1, 1)
        self.lon_WMS_eastBound_2 = QtGui.QLineEdit(self.layoutWidget_11)
        self.lon_WMS_eastBound_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lon_WMS_eastBound_2.sizePolicy().hasHeightForWidth())
        self.lon_WMS_eastBound_2.setSizePolicy(sizePolicy)
        self.lon_WMS_eastBound_2.setMinimumSize(QtCore.QSize(100, 0))
        self.lon_WMS_eastBound_2.setMaximumSize(QtCore.QSize(200, 30))
        self.lon_WMS_eastBound_2.setObjectName(_fromUtf8("lon_WMS_eastBound_2"))
        self.WMS_Bounds_10.addWidget(self.lon_WMS_eastBound_2, 1, 2, 1, 1)
        self.button_req_motu = QtGui.QPushButton(self.tab_Extract_4)
        self.button_req_motu.setEnabled(True)
        self.button_req_motu.setGeometry(QtCore.QRect(160, 400, 136, 32))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_req_motu.sizePolicy().hasHeightForWidth())
        self.button_req_motu.setSizePolicy(sizePolicy)
        self.button_req_motu.setMaximumSize(QtCore.QSize(256, 32))
        self.button_req_motu.setObjectName(_fromUtf8("button_req_motu"))
        self.combo_wms_layer_depth_max_2 = QtGui.QComboBox(self.tab_Extract_4)
        self.combo_wms_layer_depth_max_2.setGeometry(QtCore.QRect(210, 60, 150, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_wms_layer_depth_max_2.sizePolicy().hasHeightForWidth())
        self.combo_wms_layer_depth_max_2.setSizePolicy(sizePolicy)
        self.combo_wms_layer_depth_max_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.combo_wms_layer_depth_max_2.setObjectName(_fromUtf8("combo_wms_layer_depth_max_2"))
        self.ExtractWidget_4.addTab(self.tab_Extract_4, _fromUtf8(""))
        self.verticalLayout_7.addWidget(self.ExtractWidget_4)
        self.gridLayout_38.addLayout(self.verticalLayout_7, 9, 0, 1, 1)
        self.label_area_3 = QtGui.QLabel(self.scrollAreaWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_area_3.sizePolicy().hasHeightForWidth())
        self.label_area_3.setSizePolicy(sizePolicy)
        self.label_area_3.setMinimumSize(QtCore.QSize(489, 21))
        self.label_area_3.setObjectName(_fromUtf8("label_area_3"))
        self.gridLayout_38.addWidget(self.label_area_3, 1, 0, 1, 1)
        self.LoadProductButton = QtGui.QPushButton(self.scrollAreaWidgetContents_4)
        self.LoadProductButton.setObjectName(_fromUtf8("LoadProductButton"))
        self.gridLayout_38.addWidget(self.LoadProductButton, 0, 0, 1, 1)
        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_39.addWidget(self.scrollArea_7, 0, 0, 1, 1)
        self.tabWidget_Multi_WMS.addTab(self.tab, _fromUtf8(""))
        self.tab_other_wms = QtGui.QWidget()
        self.tab_other_wms.setObjectName(_fromUtf8("tab_other_wms"))
        self.gridLayout_23 = QtGui.QGridLayout(self.tab_other_wms)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.scrollArea_3 = QtGui.QScrollArea(self.tab_other_wms)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_7 = QtGui.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 508, 736))
        self.scrollAreaWidgetContents_7.setObjectName(_fromUtf8("scrollAreaWidgetContents_7"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents_7)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents_7)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 5)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.buttonManageServers = QtGui.QPushButton(self.scrollAreaWidgetContents_7)
        self.buttonManageServers.setMaximumSize(QtCore.QSize(16777215, 25))
        self.buttonManageServers.setObjectName(_fromUtf8("buttonManageServers"))
        self.horizontalLayout.addWidget(self.buttonManageServers)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.combo_dataset_list = QtGui.QComboBox(self.scrollAreaWidgetContents_7)
        self.combo_dataset_list.setMaximumSize(QtCore.QSize(16777215, 25))
        self.combo_dataset_list.setObjectName(_fromUtf8("combo_dataset_list"))
        self.verticalLayout.addWidget(self.combo_dataset_list)
        self.tree_widget = QtGui.QTreeWidget(self.scrollAreaWidgetContents_7)
        self.tree_widget.setMinimumSize(QtCore.QSize(200, 150))
        self.tree_widget.setMaximumSize(QtCore.QSize(16777215, 150))
        self.tree_widget.setObjectName(_fromUtf8("tree_widget"))
        self.verticalLayout.addWidget(self.tree_widget)
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents_7)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_WMS = QtGui.QWidget()
        self.tab_WMS.setObjectName(_fromUtf8("tab_WMS"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_WMS)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tab_WMS_layout = QtGui.QVBoxLayout()
        self.tab_WMS_layout.setObjectName(_fromUtf8("tab_WMS_layout"))
        self.combo_wms_layer = QtGui.QComboBox(self.tab_WMS)
        self.combo_wms_layer.setMaximumSize(QtCore.QSize(16777215, 25))
        self.combo_wms_layer.setObjectName(_fromUtf8("combo_wms_layer"))
        self.tab_WMS_layout.addWidget(self.combo_wms_layer)
        self.layout_wms_style = QtGui.QHBoxLayout()
        self.layout_wms_style.setSpacing(5)
        self.layout_wms_style.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.layout_wms_style.setObjectName(_fromUtf8("layout_wms_style"))
        self.comboBox = QtGui.QComboBox(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(200, 25))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.layout_wms_style.addWidget(self.comboBox)
        self.combo_wms_style_type = QtGui.QComboBox(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_wms_style_type.sizePolicy().hasHeightForWidth())
        self.combo_wms_style_type.setSizePolicy(sizePolicy)
        self.combo_wms_style_type.setMinimumSize(QtCore.QSize(100, 0))
        self.combo_wms_style_type.setMaximumSize(QtCore.QSize(200, 25))
        self.combo_wms_style_type.setObjectName(_fromUtf8("combo_wms_style_type"))
        self.layout_wms_style.addWidget(self.combo_wms_style_type)
        self.combo_wms_style_palette = QtGui.QComboBox(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_wms_style_palette.sizePolicy().hasHeightForWidth())
        self.combo_wms_style_palette.setSizePolicy(sizePolicy)
        self.combo_wms_style_palette.setMinimumSize(QtCore.QSize(100, 0))
        self.combo_wms_style_palette.setMaximumSize(QtCore.QSize(200, 25))
        self.combo_wms_style_palette.setObjectName(_fromUtf8("combo_wms_style_palette"))
        self.layout_wms_style.addWidget(self.combo_wms_style_palette)
        self.tab_WMS_layout.addLayout(self.layout_wms_style)
        self.WMSLabelTimeRange = QtGui.QLabel(self.tab_WMS)
        self.WMSLabelTimeRange.setMaximumSize(QtCore.QSize(16777215, 25))
        self.WMSLabelTimeRange.setObjectName(_fromUtf8("WMSLabelTimeRange"))
        self.tab_WMS_layout.addWidget(self.WMSLabelTimeRange)
        self.combo_wms_time = QtGui.QComboBox(self.tab_WMS)
        self.combo_wms_time.setMaximumSize(QtCore.QSize(16777215, 25))
        self.combo_wms_time.setObjectName(_fromUtf8("combo_wms_time"))
        self.tab_WMS_layout.addWidget(self.combo_wms_time)
        self.combo_wms_time_last = QtGui.QComboBox(self.tab_WMS)
        self.combo_wms_time_last.setMaximumSize(QtCore.QSize(16777215, 25))
        self.combo_wms_time_last.setObjectName(_fromUtf8("combo_wms_time_last"))
        self.tab_WMS_layout.addWidget(self.combo_wms_time_last)
        self.WMSBoundingBoxInfo = QtGui.QLabel(self.tab_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WMSBoundingBoxInfo.sizePolicy().hasHeightForWidth())
        self.WMSBoundingBoxInfo.setSizePolicy(sizePolicy)
        self.WMSBoundingBoxInfo.setMaximumSize(QtCore.QSize(16777215, 25))
        self.WMSBoundingBoxInfo.setObjectName(_fromUtf8("WMSBoundingBoxInfo"))
        self.tab_WMS_layout.addWidget(self.WMSBoundingBoxInfo)
        self.WMS_Bounds = QtGui.QGridLayout()
        self.WMS_Bounds.setSpacing(6)
        self.WMS_Bounds.setObjectName(_fromUtf8("WMS_Bounds"))
        self.WMS_eastBound = QtGui.QLineEdit(self.tab_WMS)
        self.WMS_eastBound.setEnabled(False)
        self.WMS_eastBound.setMinimumSize(QtCore.QSize(0, 25))
        self.WMS_eastBound.setMaximumSize(QtCore.QSize(16777215, 25))
        self.WMS_eastBound.setObjectName(_fromUtf8("WMS_eastBound"))
        self.WMS_Bounds.addWidget(self.WMS_eastBound, 1, 2, 1, 1)
        self.WMS_westBound = QtGui.QLineEdit(self.tab_WMS)
        self.WMS_westBound.setEnabled(False)
        self.WMS_westBound.setMinimumSize(QtCore.QSize(0, 25))
        self.WMS_westBound.setMaximumSize(QtCore.QSize(16777215, 25))
        self.WMS_westBound.setObjectName(_fromUtf8("WMS_westBound"))
        self.WMS_Bounds.addWidget(self.WMS_westBound, 1, 0, 1, 1)
        self.WMS_southBound = QtGui.QLineEdit(self.tab_WMS)
        self.WMS_southBound.setEnabled(False)
        self.WMS_southBound.setMinimumSize(QtCore.QSize(0, 25))
        self.WMS_southBound.setMaximumSize(QtCore.QSize(16777215, 25))
        self.WMS_southBound.setObjectName(_fromUtf8("WMS_southBound"))
        self.WMS_Bounds.addWidget(self.WMS_southBound, 2, 1, 1, 1)
        self.WMS_northBound = QtGui.QLineEdit(self.tab_WMS)
        self.WMS_northBound.setEnabled(False)
        self.WMS_northBound.setMinimumSize(QtCore.QSize(0, 25))
        self.WMS_northBound.setMaximumSize(QtCore.QSize(16777215, 25))
        self.WMS_northBound.setObjectName(_fromUtf8("WMS_northBound"))
        self.WMS_Bounds.addWidget(self.WMS_northBound, 0, 1, 1, 1)
        self.tab_WMS_layout.addLayout(self.WMS_Bounds)
        self.gridLayout_4.addLayout(self.tab_WMS_layout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_WMS, _fromUtf8(""))
        self.tab_WCS = QtGui.QWidget()
        self.tab_WCS.setObjectName(_fromUtf8("tab_WCS"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_WCS)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.tab_WCS_layout = QtGui.QVBoxLayout()
        self.tab_WCS_layout.setObjectName(_fromUtf8("tab_WCS_layout"))
        self.combo_wcs_coverage1 = QtGui.QComboBox(self.tab_WCS)
        self.combo_wcs_coverage1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.combo_wcs_coverage1.setObjectName(_fromUtf8("combo_wcs_coverage1"))
        self.tab_WCS_layout.addWidget(self.combo_wcs_coverage1)
        self.WCSLabelTimeRange1 = QtGui.QLabel(self.tab_WCS)
        self.WCSLabelTimeRange1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.WCSLabelTimeRange1.setObjectName(_fromUtf8("WCSLabelTimeRange1"))
        self.tab_WCS_layout.addWidget(self.WCSLabelTimeRange1)
        self.combo_wcs_time1 = QtGui.QComboBox(self.tab_WCS)
        self.combo_wcs_time1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.combo_wcs_time1.setObjectName(_fromUtf8("combo_wcs_time1"))
        self.tab_WCS_layout.addWidget(self.combo_wcs_time1)
        self.combo_wcs_time_last1 = QtGui.QComboBox(self.tab_WCS)
        self.combo_wcs_time_last1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.combo_wcs_time_last1.setObjectName(_fromUtf8("combo_wcs_time_last1"))
        self.tab_WCS_layout.addWidget(self.combo_wcs_time_last1)
        self.WCSBoundingBoxInfo = QtGui.QLabel(self.tab_WCS)
        self.WCSBoundingBoxInfo.setMaximumSize(QtCore.QSize(16777215, 25))
        self.WCSBoundingBoxInfo.setObjectName(_fromUtf8("WCSBoundingBoxInfo"))
        self.tab_WCS_layout.addWidget(self.WCSBoundingBoxInfo)
        self.WCS_Bounds = QtGui.QGridLayout()
        self.WCS_Bounds.setObjectName(_fromUtf8("WCS_Bounds"))
        self.WCS_southBound1 = QtGui.QLineEdit(self.tab_WCS)
        self.WCS_southBound1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.WCS_southBound1.setObjectName(_fromUtf8("WCS_southBound1"))
        self.WCS_Bounds.addWidget(self.WCS_southBound1, 2, 1, 1, 1)
        self.WCS_northBound1 = QtGui.QLineEdit(self.tab_WCS)
        self.WCS_northBound1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.WCS_northBound1.setObjectName(_fromUtf8("WCS_northBound1"))
        self.WCS_Bounds.addWidget(self.WCS_northBound1, 0, 1, 1, 1)
        self.WCS_westBound1 = QtGui.QLineEdit(self.tab_WCS)
        self.WCS_westBound1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.WCS_westBound1.setObjectName(_fromUtf8("WCS_westBound1"))
        self.WCS_Bounds.addWidget(self.WCS_westBound1, 1, 0, 1, 1)
        self.WCS_eastBound1 = QtGui.QLineEdit(self.tab_WCS)
        self.WCS_eastBound1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.WCS_eastBound1.setObjectName(_fromUtf8("WCS_eastBound1"))
        self.WCS_Bounds.addWidget(self.WCS_eastBound1, 1, 2, 1, 1)
        self.tab_WCS_layout.addLayout(self.WCS_Bounds)
        self.gridLayout_6.addLayout(self.tab_WCS_layout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_WCS, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout_22 = QtGui.QGridLayout()
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.button_req_map = QtGui.QPushButton(self.scrollAreaWidgetContents_7)
        self.button_req_map.setMaximumSize(QtCore.QSize(256, 23))
        self.button_req_map.setObjectName(_fromUtf8("button_req_map"))
        self.gridLayout_22.addWidget(self.button_req_map, 8, 0, 1, 1)
        self.button_req_animation = QtGui.QPushButton(self.scrollAreaWidgetContents_7)
        self.button_req_animation.setObjectName(_fromUtf8("button_req_animation"))
        self.gridLayout_22.addWidget(self.button_req_animation, 9, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_22)
        self.gridLayout_3.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_7)
        self.gridLayout_23.addWidget(self.scrollArea_3, 0, 0, 1, 1)
        self.tabWidget_Multi_WMS.addTab(self.tab_other_wms, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget_Multi_WMS, 0, 0, 1, 1)
        THREDDSViewer.setWidget(self.dockWidgetContents)

        self.retranslateUi(THREDDSViewer)
        self.tabWidget_Multi_WMS.setCurrentIndex(0)
        self.ExtractWidget_4.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(THREDDSViewer)

    def retranslateUi(self, THREDDSViewer):
        THREDDSViewer.setWindowTitle(_translate("THREDDSViewer", "ThreddsViewer", None))
        self.label_product_3.setText(_translate("THREDDSViewer", "Choose Product:", None))
        self.label_variable_3.setText(_translate("THREDDSViewer", "Choose Variable:", None))
        self.label_dataset_3.setText(_translate("THREDDSViewer", "Choose Dataset:", None))
        self.label_9.setText(_translate("THREDDSViewer", "Plot parameters :", None))
        self.label_depth_3.setText(_translate("THREDDSViewer", "Choose Depth:", None))
        self.label_style_3.setText(_translate("THREDDSViewer", "Choose Style :", None))
        self.WMSLabelTimeRange_9.setText(_translate("THREDDSViewer", "Time range to download:", None))
        self.combo_wms_time_first_h.setToolTip(_translate("THREDDSViewer", "Last time value to download for this layer\n"
"(If set, will download all the layers between the first and last times)", None))
        self.label_12.setText(_translate("THREDDSViewer", "Bounding Box:", None))
        self.checkBox_arc.setText(_translate("THREDDSViewer", "Arc", None))
        self.label_Ymedians_3.setText(_translate("THREDDSViewer", "YMedians", None))
        self.label_Xparallels_3.setText(_translate("THREDDSViewer", "XParallels", None))
        self.checkBox_ant.setText(_translate("THREDDSViewer", "Ant", None))
        self.label_minscale_3.setText(_translate("THREDDSViewer", "Min scale", None))
        self.label_nbcolors_3.setText(_translate("THREDDSViewer", "Nb colors", None))
        self.label_Xpixels_3.setText(_translate("THREDDSViewer", "Xpixels", None))
        self.label_maxscale_3.setText(_translate("THREDDSViewer", "Max scale", None))
        self.checkBox_log.setText(_translate("THREDDSViewer", "Log", None))
        self.button_req_map_plot_cmems.setText(_translate("THREDDSViewer", "Show map in view", None))
        self.button_req_animation_plot.setText(_translate("THREDDSViewer", "Show animation menu >>", None))
        self.ExtractWidget_4.setTabText(self.ExtractWidget_4.indexOf(self.tab_WMS_7), _translate("THREDDSViewer", "WMS", None))
        self.WCSLabelTimeRange.setText(_translate("THREDDSViewer", "Time range to download:", None))
        self.combo_wcs_time.setToolTip(_translate("THREDDSViewer", "First time value to download for this layer", None))
        self.combo_wcs_time_last.setToolTip(_translate("THREDDSViewer", "Last time value to download for this layer\n"
"(If set, will download all the layers between the first and last times)", None))
        self.WCSBoundingBoxInfo_7.setText(_translate("THREDDSViewer", "No bounding box info available", None))
        self.ExtractWidget_4.setTabText(self.ExtractWidget_4.indexOf(self.tab_WCS_7), _translate("THREDDSViewer", "WCS", None))
        self.ExtractWidget_4.setTabText(self.ExtractWidget_4.indexOf(self.tab_WPS_4), _translate("THREDDSViewer", "WPS", None))
        self.label_depth_6.setText(_translate("THREDDSViewer", "Choose min and max Depths:", None))
        self.WMSLabelTimeRange_10.setText(_translate("THREDDSViewer", "Time range to download:", None))
        self.combo_wms_time_first_h_2.setToolTip(_translate("THREDDSViewer", "Last time value to download for this layer\n"
"(If set, will download all the layers between the first and last times)", None))
        self.label_13.setText(_translate("THREDDSViewer", "Bounding Box:", None))
        self.button_req_motu.setText(_translate("THREDDSViewer", "Motu Request", None))
        self.ExtractWidget_4.setTabText(self.ExtractWidget_4.indexOf(self.tab_Extract_4), _translate("THREDDSViewer", "Extraction", None))
        self.label_area_3.setText(_translate("THREDDSViewer", "Choose Area:", None))
        self.LoadProductButton.setText(_translate("THREDDSViewer", "Load products", None))
        self.tabWidget_Multi_WMS.setTabText(self.tabWidget_Multi_WMS.indexOf(self.tab), _translate("THREDDSViewer", "Cmems", None))
        self.label.setText(_translate("THREDDSViewer", "Choose an available DataSet", None))
        self.buttonManageServers.setText(_translate("THREDDSViewer", "Manage servers...", None))
        self.tree_widget.headerItem().setText(0, _translate("THREDDSViewer", "SubDatasets and Maps", None))
        self.combo_wms_style_type.setToolTip(_translate("THREDDSViewer", "Style draw type", None))
        self.combo_wms_style_palette.setToolTip(_translate("THREDDSViewer", "Style color palette to use", None))
        self.WMSLabelTimeRange.setText(_translate("THREDDSViewer", "Time range to download:", None))
        self.combo_wms_time.setToolTip(_translate("THREDDSViewer", "First time value to download for this layer", None))
        self.combo_wms_time_last.setToolTip(_translate("THREDDSViewer", "Last time value to download for this layer\n"
"(If set, will download all the layers between the first and last times)", None))
        self.WMSBoundingBoxInfo.setText(_translate("THREDDSViewer", "No bounding box info available", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_WMS), _translate("THREDDSViewer", "WMS", None))
        self.WCSLabelTimeRange1.setText(_translate("THREDDSViewer", "Time range to download:", None))
        self.combo_wcs_time1.setToolTip(_translate("THREDDSViewer", "First time value to download for this layer", None))
        self.combo_wcs_time_last1.setToolTip(_translate("THREDDSViewer", "Last time value to download for this layer\n"
"(If set, will download all the layers between the first and last times)", None))
        self.WCSBoundingBoxInfo.setText(_translate("THREDDSViewer", "No bounding box info available", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_WCS), _translate("THREDDSViewer", "WCS", None))
        self.button_req_map.setText(_translate("THREDDSViewer", "Show map in view", None))
        self.button_req_animation.setText(_translate("THREDDSViewer", "Show animation menu >>", None))
        self.tabWidget_Multi_WMS.setTabText(self.tabWidget_Multi_WMS.indexOf(self.tab_other_wms), _translate("THREDDSViewer", "Others", None))

